name: ecommerce_ui_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  dio: ^5.3.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  flutter_stripe: ^9.3.0
  flutter_svg: ^2.0.7
  formz: ^0.6.0
  go_router: ^10.0.0
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  quickalert: ^1.0.1
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/cards/
    - assets/
    - .env
